const worlds={
hq:{kicker:'STRATEGIC CONTROL',title:'Main HQ',subtitle:'La cabina di comando del tuo ecosistema AI.',cards:[['⌘','Mission Control','Stato generale di agenti, mercati, rischi e workflow.','HQ online'],['◎','Agent Network','Coordina tutti gli agenti specializzati da un unico punto.','8 reparti'],['◈','Daily Focus','Priorità, eventi macro e missioni operative della giornata.','Live'],['↗','Market Pulse','Panoramica rapida di bias, volatilità e opportunità.','Real-time'],['⚡','Automation','Workflow automatici e notifiche importanti.','Coming next'],['☰','Command Log','Cronologia delle decisioni e dei task eseguiti.','Journal']]},
news:{kicker:'REAL-TIME WORLD',title:'News & Sentiment',subtitle:'Notizie, eventi macro e sentiment concentrati in un solo mondo.',cards:[['◉','Live News Feed','Flusso di notizie filtrato per impatto e strumenti che segui.','High impact'],['≈','Sentiment AI','Lettura del tono di mercato e delle narrative dominanti.','AI analysis'],['⏱','Economic Calendar','CPI, FOMC, NFP, PMI e principali eventi macro.','Calendar'],['$','USD / DXY','Area dedicata alla forza del dollaro e alle correlazioni.','Macro'],['₿','Crypto Desk','Notizie e sentiment per Bitcoin e asset crypto selezionati.','Crypto'],['✦','Impact Map','Quali mercati possono essere più sensibili a ogni evento.','Cross-asset']]},
macro:{kicker:'BIG PICTURE',title:'Macro Analysis',subtitle:'Il quadro generale prima di guardare il singolo setup.',cards:[['◫','Weekly Bias','Scenario macro settimanale con fattori favorevoli e contrari.','Weekly'],['◇','Rates & Central Banks','Tassi, aspettative e comunicazione delle banche centrali.','Rates'],['△','Inflation & Growth','Inflazione, occupazione, crescita e sorprese macro.','Macro data'],['↔','Intermarket','DXY, rendimenti, oro, indici e correlazioni principali.','Cross-market'],['◎','Risk Regime','Risk-on / risk-off e cambiamenti del regime di mercato.','Regime'],['✦','Macro Notes','Tesi, scenari e invalidazioni salvate nel tempo.','Research']]},
scanner:{kicker:'OPPORTUNITIES',title:'Market Scanner',subtitle:'Scansiona i mercati e porta in superficie solo ciò che merita attenzione.',cards:[['⌖','Setup Radar','Lista dei mercati con condizioni tecniche interessanti.','Scanner'],['↯','Liquidity Watch','Sweep e aree dove può concentrarsi la liquidità.','Liquidity'],['▥','FVG / OB Finder','Zone di imbalance, fair value gap e order block.','SMC'],['↗','Structure Shift','BOS, CHoCH e cambiamenti della struttura multi-timeframe.','Structure'],['★','Setup Score','Confluenze visualizzate senza sostituire la tua decisione.','Confluence'],['☷','Filters','Asset, timeframe, sessione e criteri personalizzati.','Custom']]},
chart:{kicker:'MULTI-TIMEFRAME',title:'Chart Analysis',subtitle:'Un ambiente dedicato alla lettura tecnica dei grafici.',cards:[['▥','Top-down View','Monthly, Weekly, Daily, H4 e timeframe di conferma.','MTF'],['↳','Market Structure','Swing, BOS, CHoCH e livelli chiave.','Structure'],['◇','Supply / Demand','Zone di interesse e aree di reazione.','Zones'],['⌁','Fibonacci','Livelli di retracement e confluence.','0.618'],['∿','EMA Context','Contesto trend con medie mobili selezionate.','EMA'],['✎','Trade Thesis','Salva tesi, conferme, invalidazione e target.','Journal']]},
risk:{kicker:'DISCIPLINE',title:'Risk & Money',subtitle:'Protezione del capitale, sizing e disciplina prima dell’esecuzione.',cards:[['盾','Risk Calculator','Calcolo della size in base al rischio scelto.','Sizing'],['%','Exposure','Rischio totale e correlazione tra posizioni aperte.','Portfolio'],['↓','Drawdown Guard','Soglie e limiti per proteggere il conto.','Protection'],['1:2','R:R Planner','Pianificazione di stop, target e rapporto rischio/rendimento.','Planning'],['✓','Prop Rules','Regole operative e limiti dei conti prop.','Rules'],['◷','Performance','Rischio medio, loss streak e metriche operative.','Stats']]},
data:{kicker:'INSIGHTS',title:'Data & Research',subtitle:'Dati, note e ricerca per capire cosa sta davvero funzionando.',cards:[['▦','Trade Database','Archivio strutturato dei trade e dei setup.','Database'],['∑','Statistics','Win rate, expectancy, R-multiple e distribuzioni.','Analytics'],['◎','Pattern Research','Confronta setup e condizioni ricorrenti.','Research'],['⌕','Search','Ricerca veloce tra note, trade ed eventi.','Index'],['⇄','Correlations','Relazioni tra coppie, DXY, oro, indici e macro.','Cross-asset'],['◌','Experiments','Backtest e test controllati della strategia.','Lab']]},
dev:{kicker:'BUILD & IMPROVE',title:'Development',subtitle:'Il laboratorio dove costruiamo e miglioriamo RS_AI Trading Lab.',cards:[['</>','Agent Builder','Configura ruoli, prompt, input e output degli agenti.','Agents'],['⚙','Workflows','Collega agenti e automazioni in pipeline operative.','Automation'],['API','Integrations','Area per Dify, feed dati, broker API e servizi esterni.','Connect'],['▣','Interface Lab','Prototipi della dashboard e dei mondi interattivi.','UI / UX'],['↻','Versions','Roadmap, changelog e versioni del progetto.','Build'],['✓','System Health','Stato delle integrazioni e controlli del sistema.','Monitor']]},
journal:{kicker:'REFLECT · IMPROVE',title:'Journal',subtitle:'Pensieri, trade, errori e lezioni raccolti in un unico spazio.',cards:[['✎','New Entry','Crea una nuova nota di trading.','Journal'],['▤','Trade Review','Rivedi esecuzione, logica e risultato.','Review'],['★','Lessons','Salva le lezioni che vuoi ricordare.','Learning'],['◷','Timeline','Sfoglia il tuo percorso nel tempo.','History'],['⌕','Search Notes','Trova rapidamente una vecchia idea.','Search'],['↗','Growth','Osserva come cambia la qualità delle tue decisioni.','Progress']]},
watchlist:{kicker:'TRACK · ANALYZE',title:'Watchlist',subtitle:'I mercati che vuoi tenere sotto controllo senza rumore inutile.',cards:[['€','EURUSD','Bias, livelli e note personali.','FX'],['£','GBPUSD','Bias, livelli e note personali.','FX'],['◉','XAUUSD','Oro, DXY e livelli chiave.','Gold'],['$','USDCAD','USD, petrolio e struttura.','FX'],['¥','USDJPY','Dollaro, rendimenti e JPY.','FX'],['₿','BTCUSD','Bitcoin e struttura principale.','Crypto']]},
sessions:{kicker:'GLOBAL CLOCK',title:'Market Sessions',subtitle:'Vedi rapidamente quale parte del mercato è attiva.',cards:[['◷','Sydney','Sessione Asia-Pacifico.','Session'],['◷','Tokyo','Liquidità asiatica e JPY.','Session'],['◷','London','Apertura europea e maggiore attività FX.','Session'],['◷','New York','Sessione USA e sovrapposizione con Londra.','Session'],['◎','Overlap','Finestre di maggiore partecipazione.','Timing'],['⚡','News Windows','Eventi macro durante le sessioni.','Calendar']]},
settings:{kicker:'PERSONALIZE',title:'Settings',subtitle:'Personalizza il tuo laboratorio e le sue preferenze.',cards:[['◐','Appearance','Tema, effetti e densità dell’interfaccia.','UI'],['☷','Markets','Strumenti e watchlist predefinite.','Preferences'],['♙','Agents','Ruoli e comportamento degli agenti.','AI'],['⚙','Integrations','Connessioni a servizi e API.','Connect'],['🔔','Notifications','Regole e priorità degli avvisi.','Alerts'],['🔒','Privacy','Controlli e impostazioni di sicurezza.','Security']]}
};
const panel=document.getElementById('worldPanel'),title=document.getElementById('worldTitle'),subtitle=document.getElementById('worldSubtitle'),kicker=document.getElementById('worldKicker'),grid=document.getElementById('worldGrid'),viewport=document.getElementById('viewport'),scene=document.getElementById('scene');
function openWorld(key){const data=worlds[key]||worlds.hq;kicker.textContent=data.kicker;title.textContent=data.title;subtitle.textContent=data.subtitle;grid.innerHTML=data.cards.map(([icon,name,desc,chip])=>`<article class="world-card"><div class="card-icon">${icon}</div><h3>${name}</h3><p>${desc}</p><span class="card-chip">${chip}</span></article>`).join('');panel.classList.add('open');panel.setAttribute('aria-hidden','false');history.replaceState(null,'',`#${key}`)}
function closeWorld(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');history.replaceState(null,'',location.pathname)}
document.querySelectorAll('[data-world]').forEach(el=>el.addEventListener('click',()=>openWorld(el.dataset.world)));
document.querySelectorAll('[data-action="home"],[data-action="world"]').forEach(el=>el.addEventListener('click',closeWorld));
document.getElementById('backBtn').addEventListener('click',closeWorld);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('open'))closeWorld()});
function centerMobile(){if(scene.scrollWidth&&viewport.clientWidth<scene.clientWidth){viewport.scrollLeft=Math.max(0,(scene.clientWidth-viewport.clientWidth)/2)}}
window.addEventListener('load',()=>{centerMobile();const hash=location.hash.replace('#','');if(hash&&worlds[hash])openWorld(hash)});
window.addEventListener('resize',centerMobile);